Личный проект: генератор публикаций
htmlacademy-nodejs/11545-typoteka-3 pull request #3
Opened 2021-07-25 15:41 UTC by johnnypiston

2021-07-25 18:02 UTC, dean992008 requested changes

2021-07-25 18:02 UTC, dean992008 commented on src/constants.js
> +  success: 0,
Коментарии из учебного проекта актуальны и для личного.

2021-07-25 18:02 UTC, dean992008 commented on src/service/cli/generate.js
> +    fullText: Array(getRandomInt(TextRestrict.MIN, TextRestrict.MAX)).fill(``).map(() => SENTENCES[getRandomInt(0, SENTENCES.length - 1)]).join(` `),
Мне кажется что использовать здесь `shuffle` было бы более уместно.

2021-07-25 18:02 UTC, dean992008 commented on src/utils.js
> +  return `${[newDate.getFullYear(), newDate.getMonth() + 1, newDate.getDate()].map((number) => `${number}`.padStart(2, `0`)).join(`-`)} ${[newDate.getHours(), newDate.getMinutes(), newDate.getSeconds
Я думаю форматирование даты делать пока лишее и можно возвращять в unix формате. Форматировать будет на фронт сервере с помощью библиотек.

2021-07-26 11:32 UTC, johnnypiston commented on src/service/cli/generate.js
> +    fullText: Array(getRandomInt(TextRestrict.MIN, TextRestrict.MAX)).fill(``).map(() => SENTENCES[getRandomInt(0, SENTENCES.length - 1)]).join(` `),
Тут идея заключалась в том, что можно создать текст из произвольного количества предложений. Просто используя `shuffle` можно добиться количества равного длине массива предложений.
Меня на такую реализацию натолкнул текст задания:
_"Полный текст может включать произвольное количество предложений. Предложения берутся случайным образом. Предложения могут повторяться."_
Но если не стоит так заморачиваться, то переделаю на `shuffle`.

2021-07-26 11:37 UTC, dean992008 commented on src/service/cli/generate.js
> +    fullText: Array(getRandomInt(TextRestrict.MIN, TextRestrict.MAX)).fill(``).map(() => SENTENCES[getRandomInt(0, SENTENCES.length - 1)]).join(` `),
Вприницпе можно оставить и эту реализацию, хотя я бы не засорачивался и сделал `shuffle`

2021-07-26 13:27 UTC, merged